apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mqtt.fullname" . }}-certs
  labels:
{{ include "mqtt.labels" . | indent 4 }}
data:
  ca.crt: |-
    {{- .Values.certs.ca.crt | nindent 4 }}
  server.crt: |-
    {{- .Values.certs.server.crt | nindent 4 }}
  server.key: |-
    {{- .Values.certs.server.key | nindent 4 }}
