{{- if .Values.ingress.enabled -}}
{{- $fullName := include "mqtt.fullname" . -}}
{{- $svcPort := .Values.service.ports.mqtt.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "mqtt.labels" . | nindent 4 }}
  annotations:
    kubernate.io/ingress.class: ngnix
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    kubernetes.io/ingress.class: "elb-internal"  
spec:
  rules:
    - host: {{ .Values.global.env.HOST }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
  {{end}}